site_name: datascribe_api
repo_url: https://github.com/DataScribe-Cloud/datascribe_api/
repo_name: DataScribe-Cloud/datascribe_api

theme:
  name: material
  logo: img/logo-light.ico
  favicon: img/favicon.ico
  palette:
    - scheme: custom-light
      toggle:
      primary: custom
      accent: custom
  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.footer
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/style.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - tables

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_bases: false
            show_source: false
            parameter_headings: true
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_toc: true
            show_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Overview: overview.md
  - Installation & Quick Start:
    - installation/index.md
    - installation/api.md
    - installation/cli.md
  - API Endpoints: endpoints.md
  - CLI Usage: cli.md
  - Models:
    - models/index.md
    - models/DataTable.md
    - models/DataTables.md
    - models/DataTableColumns.md
    - models/DataTableMetadata.md
    - models/DataTableRows.md
    - models/DataTableRowsCount.md
    - models/MaterialByIdResults.md
    - models/MaterialSearchResults.md
  - API Reference: api_reference.md
