name: Test Filter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_cli:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          DATASCRIBE_API_TOKEN: ${{ secrets.DATASCRIBE_API_TOKEN }}
          DATASCRIBE_ADMIN_API_TOKEN: ${{ secrets.DATASCRIBE_ADMIN_API_TOKEN }}
        run: |
          uv run python -m unittest tests/test_filter.py
